// Generated by CoffeeScript 1.6.3
/*
	Copyright 2013 David Pearson.
	BSD License.
*/


(function() {
  var assert, gelim, matrix, vows;

  assert = require("assert");

  vows = require("vows");

  gelim = require("../lib/gelim");

  matrix = require("../lib/matrix");

  vows.describe("Gaussian Elimination").addBatch({
    "something": {
      topic: function() {
        return gelim.gelim([[2, 1, -1, 8], [-3, -1, 2, -11], [-2, 1, 2, -3]]);
      },
      "We get a two-dimensional array": function(topic) {
        return assert.isTrue(Object.prototype.toString.call(topic) === "[object Array]" && (topic[0] != null) && Object.prototype.toString.call(topic[0]) === "[object Array]");
      },
      "We get a 3x4 matrix": function(topic) {
        return assert.isTrue(topic.length === 3 && topic[0].length === 4);
      },
      "We get the correct solution": function(topic) {
        return assert.isTrue(matrix.equals(topic, [[1, 0.3333333333333333, -0.6666666666666666, 3.6666666666666665], [0, 1, 0.4000000000000001, 2.6], [0, 0, 1, -0.9999999999999999]]));
      }
    }
  })["export"](module);

}).call(this);
